#!/usr/bin/zsh

# -------------------------------------------------------------------
# General
# -------------------------------------------------------------------

alias history='fc -fl 1'

# Shortcuts
alias zshrc="$EDITOR ~/.config/zsh"

# Mirrors
alias mirrors="sudo reflector --verbose --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist"

#Arch
alias install="sudo pacman -S --noconfirm "
alias remove="sudo pacman -Rs "
alias update="sudo pacman -Syu && yay -Syu && exit"

#Terminal
alias ex="exit"

#Dev Related
alias code.="code . && exit"
alias ni="npm install"
alias nr="npm run dev"
alias ns="npm start"

# Git
alias clone="git clone"

#Others
alias pingg="ping google.com"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

#Python
alias pm="python manage.py"
alias pv="python -m venv ./venv"
alias pi="pip install"
alias ps="source venv/bin/activate"
alias pmm="pm migrate"
alias pmc="pm createsuperuser"
alias pmr="pm runserver"
alias pir="pi -r requirements.txt"
alias pinitial="pv && ps && pir"
