#!/usr/bin/zsh

# -------------------------------------------------------------------
# General
# -------------------------------------------------------------------

alias history='fc -fl 1'

# Shortcuts
alias zshrc="$EDITOR $ZSHRC"

# Mirrors
alias mirrors="sudo reflector --verbose --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist"

#Arch
alias install="sudo pacman -S "
alias remove="sudo pacman -Rs "
alias update="sudo pacman -Syu && yay -Syu && exit"

#Terminal
alias ex="exit"

#Dev Related
alias code.="code . && exit"
alias ni="npm install"
alias nr="npm run dev"
alias ns="npm start"

#Config
alias zshrc="code ~/.zshrc && exit"

# Git
alias clone="git clone"

#Others
alias pingg="ping google.com"

#Python
alias pm="python manage.py"
alias pvenv="python -m venv ./venv"
alias pi="pip install"
alias ps="source venv/bin/activate"
