#!/usr/bin/sh

# Node, Npm, Nvm
declare -a NODE_GLOBALS=(`find ~/.local/share/nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)

NODE_GLOBALS+=("node")
NODE_GLOBALS+=("nvm")
NODE_GLOBALS+=("yarn")

load_nvm () {
    source /usr/share/nvm/init-nvm.sh
}

for cmd in "${NODE_GLOBALS[@]}"; do
    eval "${cmd}(){ unset -f ${NODE_GLOBALS}; load_nvm; ${cmd} \$@ }"
done
unset cmd NODE_GLOBALS
